### ISSUE TITLE
Posible fallo en mover rey

### ISSUE THREAD

**Issue by Adriang2211** [Adriang2211/Hombres-gg#27]
Se ha detectado un posible fallo en el movimiento del rey. Tras mover el rey blanco, con una posterior actualización del vector de movimientos posibles no sale ningún movimiento posible.
El fallo puede deberse a que se detecte erróneamente que la casilla contigua esté bajo ataque, algún fallo que hasta ahora no se hubiese detectado en las funciones de enroque o de movimientos del rey o a la propia función de mover el rey.

**Comment by Joshgv25** [comment]
Está corregido
